version: '3'

networks:

  default:
    internal: true
  traefik:
    external:
      name: traefik

services:

  gatsby:
    build: ./services/gatsby
    env_file: .env
    labels:
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.http.routers.net-ouiedire-gatsby-gatsby.entrypoints=web
      - traefik.http.routers.net-ouiedire-gatsby-gatsby.rule=Host(`net.ouiedire.gatsby.localhost`)
    networks:
      - default
      - traefik
    volumes:
      - ./services/gatsby/src:/usr/src/app
