version: '3'

services:

    portainer:
        image: portainer/portainer:1.24.1-alpine
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.entrypoints=web"
            - "traefik.http.routers.portainer.rule=Host(`portainer.net-ouiedire-gatsby.localhost`)"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"

    traefik:
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        image: traefik:v2.2.8
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.entrypoints=web"
            - "traefik.http.routers.traefik.rule=Host(`traefik.net-ouiedire-gatsby.localhost`)"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

            